INSERT INTO day (id) VALUES ('2025-08-29');
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Early rise',                 1, '2025-08-29', 1,  1);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Home cleaning',              2, '2025-08-29', 1,  2);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Shower',                     4, '2025-08-29', 1,  3);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Hair care',                  5, '2025-08-29', 1,  4);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Face shave',                 6, '2025-08-29', 1,  5);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Dental care (after sleep)',  3, '2025-08-29', 1,  6);
INSERT INTO day (id) VALUES ('2025-08-31');
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Early rise',                 1, '2025-08-31', 1,  1);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Home cleaning',              2, '2025-08-31', 1,  2);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Nail care',                  7, '2025-08-31', 1,  3);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Hair care',                  5, '2025-08-31', 1,  4);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Face shave',                 6, '2025-08-31', 1,  5);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Dental care (after sleep)',  3, '2025-08-31', 1,  6);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Shower',                     4, '2025-08-31', 0,  7);
INSERT INTO day (id) VALUES ('2025-09-01');
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Early rise',                 1, '2025-09-01', 1,  1);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Home cleaning',              2, '2025-09-01', 1,  2);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Shower',                     4, '2025-09-01', 1,  3);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Hair care',                  5, '2025-09-01', 1,  4);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Face shave',                 6, '2025-09-01', 1,  5);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Dental care (after sleep)',  3, '2025-09-01', 1,  6);
INSERT INTO day (id) VALUES ('2025-09-02');
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Early rise',                 1, '2025-09-02', 1,  1);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Home cleaning',              2, '2025-09-02', 1,  2);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Hair care',                  5, '2025-09-02', 1,  3);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Face shave',                 6, '2025-09-02', 1,  4);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Dental care (after sleep)',  3, '2025-09-02', 1,  5);
INSERT INTO day (id) VALUES ('2025-09-03');
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Early rise',                 1, '2025-09-03', 1,  1);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Home cleaning',              2, '2025-09-03', 1,  2);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Dental care (after sleep)',  3, '2025-09-03', 1,  3);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Face shave',                 6, '2025-09-03', 1,  4);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Shower',                     4, '2025-09-03', 1,  5);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Hair care',                  5, '2025-09-03', 1,  6);
INSERT INTO day (id) VALUES ('2025-09-04');
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Early rise',                 1, '2025-09-04', 1,  1);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Home cleaning',              2, '2025-09-04', 1,  2);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Hair care',                  5, '2025-09-04', 1,  3);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Face shave',                 6, '2025-09-04', 1,  4);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Dental care (after sleep)',  3, '2025-09-04', 1,  5);
INSERT INTO day (id) VALUES ('2025-09-05');
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Early rise',                 1, '2025-09-05', 1,  1);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Home cleaning',              2, '2025-09-05', 1,  2);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Shower',                     4, '2025-09-05', 1,  3);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Hair care',                  5, '2025-09-05', 1,  4);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Face shave',                 6, '2025-09-05', 1,  5);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Dental care (after sleep)',  3, '2025-09-05', 1,  6);
INSERT INTO day (id) VALUES ('2025-09-06');
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Early rise',                 1, '2025-09-06', 0,  1);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Home cleaning',              2, '2025-09-06', 1,  2);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Hair care',                  5, '2025-09-06', 1,  3);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Face shave',                 6, '2025-09-06', 1,  4);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Dental care (after sleep)',  3, '2025-09-06', 1,  5);
INSERT INTO day (id) VALUES ('2025-09-07');
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Early rise',                 1, '2025-09-07', 0,  1);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Nail care',                  7, '2025-09-07', 1,  2);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Home cleaning',              2, '2025-09-07', 1,  3);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Shower',                     4, '2025-09-07', 1,  4);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Hair care',                  5, '2025-09-07', 1,  5);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Face shave',                 6, '2025-09-07', 1,  6);
INSERT INTO rule_instance (rule_name, rule_schedule_id, day_id, done, order_priority) VALUES ('Dental care (after sleep)',  3, '2025-09-07', 1,  7);
